// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uthskomnelnrfrlhytab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0aHNrb21uZWxucmZybGh5dGFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTcyNDQsImV4cCI6MjA3Mzg3MzI0NH0.xgaBlNsOOrtVeIN6eQbTJjN9aLucArZAX0_-ikB-tyQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});